### ISSUE TITLE
What about REDIR301 and REDIR302 types?

### ISSUE THREAD

**Issue by gaalferov** [Domain-Connect/DomainConnectApplyZone#5]
These two types doesn't support now?

https://github.com/Domain-Connect/DomainConnectApplyZone/blob/2ed379e01097bc9d80c288120f422c4323b88ad9/domainconnectzone/DomainConnect.py#L404

Template: https://github.com/Domain-Connect/Templates/blob/42d5e22faea25261ffd81882a1d3089ac1eba195/smugmug.com.site.json#L12

**Comment by arnoldblinn** [comment]
The DomainConnectApplyZone is only a partial implementation of the work a DNS Provider needs.  There are some obvious elements of this around the UX and consent parts of the flow, authorization of access to the zone, and of course reading and write the resulting zone into whatever the DNS Provider is using for DNS.

In a nutshell, this project handles the merging of the records into a zone and apply variables and template rules.

The "redir" commands (which are optional in the spec, btw) pose an interesting challenge.  Many DNS Providers will have their own implementation of a redirect service.  Remember, a redirect typically requires two components.  One is setting the A record to a specific value of their redirect service. The other is adding an entry to their 'database' of where redirects should navigate.

We could add some support to this library for the redirect command; mainly treating it like an A record in terms of conflict detection and variable processing. But the library still wouldn't know the target IP, and it wouldn't be able to add the redirect to the database. 

Instead, it is envisioned that the calling DNS Provider implement this outside this library.  That is to say if they choose to implement this optional element of the specification....
